### ISSUE TITLE
在swoole里使用的几个问题

### ISSUE THREAD

**Issue by jasonhe88** [Janson-Leung/nsq-swoole#1]
正在找swoole的nsq客户端，，，谢谢！！！

有几个问题想明白一下：

1. 这个用到了swoole的异步TCP客户端，那就只能在异步模式的的swoole里使用，不能在同步swoole server使用，对吧

2. 我的理解是一个对于一个nsq topic, swoole server应该只有一个client 来订阅消息，那这个client应该只放在一个swoole worker里。那有没有可能加入swoole的异步event loop， 由多个worker来均衡处理nsqd发过来的消息？

再次感谢！

jason

**Comment by Janson-Leung** [comment]
1. 与server的模式无关，server无同异步模式这一说
2. nsq消费者采用异步客户端，swoole底层已经是基于epoll模式
3. 同一个worker进程里可以起多个消费者，即可以订阅多个topic或单个topic多个消费者，均衡处理可以放在task进程里处理，即worker订阅消息后交给task进程处理业务逻辑
