### ISSUE TITLE
发送消息出现 Broken Pipe 警告

### ISSUE THREAD

**Issue by jasonhe88** [Janson-Leung/nsq-swoole#2]
在Producer发送数据时， 会经常出现如下错误：

PHP Warning:  swoole_client::send(): send(36) 5 bytes failed. Error: Broken pipe[32]. in /home/jasonhe/C1/vendor/janson-leung/nsq-swoole/src/Monitor/Producer.php on line 36

**Comment by Janson-Leung** [comment]
服务端连接被关闭后再次send会出现这种警告，有重试机制，已忽略警告抛出
