### ISSUE TITLE
Lookup 失败

### ISSUE THREAD

**Issue by jasonhe88** [Janson-Leung/nsq-swoole#3]
在 Lookup.php 里

$producers = isset($result['data']['producers']) ? $result['data']['producers'] : [];

这行将返回空数组，因为curl_exec($ch) 返回结果里没有 'data' 项，改为如下：

$producers = isset($result['producers']) ? $result['producers'] : [];

**Comment by Janson-Leung** [comment]
基于 nsq  V2协议版本开发，数据结构如下：

> array(3) {
　["status_code"]=>
　int(200)
　["status_txt"]=>
　string(2) "OK"
　["data"]=>
　array(2) {
　　["channels"]=>
　　array(1) {
　　　[0]=>
　　　string(3) "web"
　　}
　　["producers"]=>
　　array(2) {
　　　[0]=>
　　　array(6) {
　　　　["remote_address"]=>
　　　　string(17) "192.168.1.50:9488"
　　　　["hostname"]=>
　　　　string(6) "dev-50"
　　　　["broadcast_address"]=>
　　　　string(12) "192.168.1.50"
　　　　["tcp_port"]=>
　　　　int(4150)
　　　　["http_port"]=>
　　　　int(4151)
　　　　["version"]=>
　　　　string(5) "0.3.8"
　　　}
　　　[1]=>
　　　array(6) {
　　　　["remote_address"]=>
　　　　string(18) "192.168.1.51:38168"
　　　　["hostname"]=>
　　　　string(6) "dev-51"
　　　　["broadcast_address"]=>
　　　　string(12) "192.168.1.51"
　　　　["tcp_port"]=>
　　　　int(4150)
　　　　["http_port"]=>
　　　　int(4151)
　　　　["version"]=>
　　　　string(5) "0.3.8"
　　　}
　　}
　}
}
